---
title: 参数配置
---

flowchart TD
    A(设备SDK初始化<br><strong>NET_SDK_Init</strong>)
    B(用户注册设备<br><strong>NET_SDK_Login</strong>或<br><strong>NET_SDK_LoginEx</strong>)
    C("修改设备系统时间<br><strong>NET_SDK_ChangeTime</strong>")
    D("修改设备网络配置<br><strong>NET_SDK_ModifyDeviceNetInfo</strong>")
    E(注销设备<br><strong>NET_SDK_Logout</strong>)
    F(释放SDK资源<br><strong>NET_SDK_Cleanup</strong>)

    B --> C --> E
    A --> B --> D --> E --> F
    