---
title: 录像回放
---

flowchart TD
    A(设备SDK初始化<br><strong>NET_SDK_Init</strong>)
    B(用户注册设备<br><strong>NET_SDK_Login</strong>或<br><strong>NET_SDK_LoginEx</strong>)

    subgraph 查找录像文件
        direction LR
        S0(查找录像文件<br><strong>NET_SDK_FindFile</strong>)
        S1(逐个获取录像文件信息<br><strong>NET_SDK_FindNextFile</strong>)
        S2(停止录像查找<br><strong>NET_SDK_FindClose</strong>)
        S0 --> S1 --> S2
    end

    subgraph 录像文件回放
        direction LR
        S00(按时间回放<br><strong>NET_SDK_PlayBackByTime</strong>)
        S01(回放状态控制<br><strong>NET_SDK_PlayBackControl</strong>)
        S02(停止录像回放<br><strong>NET_SDK_StopPlayBack</strong>)
        S00 --> S01 --> S02
    end


    E(注销设备<br><strong>NET_SDK_Logout</strong>)
    F(释放SDK资源<br><strong>NET_SDK_Cleanup</strong>)

    A --> B --> 查找录像文件 --> 录像文件回放 --> E --> F
    