/**
 * Configuración por defecto de la app tableta (instalación nueva / reset).
 * Ajustar aquí los valores de fábrica.
 */
import type { ConfigurationData } from '@/types/configurationData';

export const DEFAULT_DOOR_APP_CONFIGURATION: ConfigurationData = {
  doors: [
    {
      enabled: true,
      name: 'Calle (P1)',
      ipExterior: '192.168.1.80',
      ipInterior: '',
      intercom: {
        name: 'Intercomunicador Calle (P1)',
        cameraIP: '192.168.1.80',
        httpPort: 80,
        httpsPort: 443,
        onvifUsername: 'admin',
        onvifPassword: 'panphone',
        rtspPort: 554,
        sdkPort: 9008,
        sdkUsername: 'admin',
        sdkPassword: 'Santander@01',
        voiceChannel: -1,
        intercomMode: 'sip',
        bridgeUrl: 'ws://192.168.1.155:8765',
        videoProfile: 'MainStream',
        snapshotPath: 'camara.php',
        // Tablet fábrica = ext 201. Tablet2: cambiar a 202 / Santander202 en Intercom.
        sipUri: 'sip:201@192.168.1.154',
        sipUsername: '201',
        sipPassword: 'Santander201',
        sipDomain: '192.168.1.154',
        sipServer: '192.168.1.154:8088/ws',
        // Panphone Calle FreePBX ext 101
        sipCallDestination: 'sip:101@192.168.1.154',
        sipSignaling: 'pbx',
        sipP2pPeerIp: '',
        csipApiHost: '192.168.1.80:8090',
        csipApiUseHttps: false,
        csipApiKey: 'f3fb37ac959b795507cf3d6794b1f29b91ed2b1b1d1f06c6',
        csipBearerToken: '',
        csipCallTargetType: 'default',
        csipCallTarget: '',
        csipCallUser: '',
        csipCallRecording: false,
        csipButtonId: 'p1',
        enableOnvifEvents: true,
        enableTLS: false,
        preferredResolution: '1920x1080',
        preferredFPS: 25,
        defaultOpenTime: 5,
        doorControlUsername: 'ceroideas',
        doorControlPassword: '12345678',
        doorControlPCB: 2,
        doorControlSwitch: 7,
        rtspPath: 'video1',
        doorControlManualMode: false,
        doorControlPulseTime: 1,
        hasAudio: true,
        doorControlAction: 'door_endpoint',
        doorControlEndpoint: 'api/v1/door/open/p1',
        doorControlRuleKey: '',
        doorOutputMode: 'auto',
      },
    },
    {
      enabled: true,
      name: 'Oficina (P2)',
      ipExterior: '192.168.1.70',
      ipInterior: '',
      intercom: {
        name: 'Intercomunicador Oficina (P2)',
        cameraIP: '192.168.1.70',
        httpPort: 80,
        httpsPort: 443,
        onvifUsername: 'admin',
        onvifPassword: 'panphone',
        rtspPort: 554,
        sdkPort: 9008,
        sdkUsername: 'admin',
        sdkPassword: 'Santander@01',
        voiceChannel: -1,
        intercomMode: 'sip',
        bridgeUrl: 'ws://192.168.1.155:8765',
        videoProfile: 'MainStream',
        snapshotPath: 'camara.php',
        sipUri: 'sip:201@192.168.1.154',
        sipUsername: '201',
        sipPassword: 'Santander201',
        sipDomain: '192.168.1.154',
        sipServer: '192.168.1.154:8088/ws',
        // Panphone Oficina FreePBX ext 100
        sipCallDestination: 'sip:100@192.168.1.154',
        sipSignaling: 'pbx',
        sipP2pPeerIp: '',
        csipApiHost: '192.168.1.70:8090',
        csipApiUseHttps: false,
        csipApiKey: 'f3fb37ac959b795507cf3d6794b1f29b91ed2b1b1d1f06c6',
        csipBearerToken: '',
        csipCallTargetType: 'default',
        csipCallTarget: '',
        csipCallUser: '',
        csipCallRecording: false,
        csipButtonId: 'p2',
        enableOnvifEvents: true,
        enableTLS: false,
        preferredResolution: '1920x1080',
        preferredFPS: 25,
        defaultOpenTime: 5,
        doorControlUsername: 'ceroideas',
        doorControlPassword: '12345678',
        doorControlPCB: 3,
        doorControlSwitch: 7,
        rtspPath: 'video1',
        doorControlManualMode: false,
        doorControlPulseTime: 1,
        hasAudio: true,
        doorControlAction: 'door_endpoint',
        doorControlEndpoint: 'api/v1/door/open/p2',
        doorControlRuleKey: '',
        doorOutputMode: 'auto',
      },
    },
    {
      enabled: false,
      name: 'Puerta 3',
      ipExterior: '127.0.0.1',
      ipInterior: '',
      intercom: {
        name: 'Intercomunicador Puerta 3',
        cameraIP: '192.168.1.120',
        httpPort: 80,
        httpsPort: 443,
        onvifUsername: 'ceroideas',
        onvifPassword: 'Cero21264712-',
        rtspPort: 554,
        videoProfile: 'MainStream',
        snapshotPath: 'cgi-bin/snapshot.cgi?channel=1',
        sipUri: '',
        sipUsername: '',
        sipPassword: '',
        sipDomain: '',
        enableOnvifEvents: true,
        enableTLS: false,
        preferredResolution: '1920x1080',
        preferredFPS: 25,
        defaultOpenTime: 5,
        doorControlUsername: 'ceroideas',
        doorControlPassword: '12345678',
        doorControlPCB: 1,
        doorControlSwitch: 5,
        rtspPath: 'trackID=1',
        hasAudio: false,
        doorControlAction: 'set_output',
        doorControlRuleKey: '',
        doorOutputMode: 'auto',
        doorControlPulseTime: 1,
      },
    },
    {
      enabled: false,
      name: 'Puerta 4',
      ipExterior: '',
      ipInterior: '',
      intercom: {
        name: 'Intercomunicador Puerta 4',
        cameraIP: '',
        httpPort: 80,
        httpsPort: 443,
        onvifUsername: 'ceroideas',
        onvifPassword: 'Cero21264712-',
        rtspPort: 554,
        videoProfile: 'MainStream',
        sipUri: '',
        sipUsername: '',
        sipPassword: '',
        sipDomain: '',
        enableOnvifEvents: true,
        enableTLS: false,
        preferredResolution: '1920x1080',
        preferredFPS: 25,
        defaultOpenTime: 5,
        doorControlUsername: 'ceroideas',
        doorControlPassword: '12345678',
        doorControlPCB: 1,
        doorControlSwitch: 4,
        doorControlAction: 'set_output',
        doorControlRuleKey: '',
        doorOutputMode: 'auto',
        doorControlPulseTime: 1,
      },
    },
    {
      enabled: false,
      name: 'Puerta 5',
      ipExterior: '',
      ipInterior: '',
      intercom: {
        name: 'Intercomunicador Puerta 5',
        cameraIP: '',
        httpPort: 80,
        httpsPort: 443,
        onvifUsername: 'ceroideas',
        onvifPassword: 'Cero21264712-',
        rtspPort: 554,
        videoProfile: 'MainStream',
        sipUri: '',
        sipUsername: '',
        sipPassword: '',
        sipDomain: '',
        enableOnvifEvents: true,
        enableTLS: false,
        preferredResolution: '1920x1080',
        preferredFPS: 25,
        defaultOpenTime: 5,
        doorControlUsername: 'ceroideas',
        doorControlPassword: '12345678',
        doorControlPCB: 1,
        doorControlSwitch: 5,
        doorControlAction: 'set_output',
        doorControlRuleKey: '',
        doorOutputMode: 'auto',
        doorControlPulseTime: 1,
      },
    },
  ],
  network: {
    consoleIP: '192.168.1.155',
    netmask: '255.255.255.0',
    gateway: '0.0.0.0',
  },
  api: {
    port: 8000,
    username: 'ceroideas',
    password: '12345678',
    urlToken: '/api/v1/auth/token',
    urlGet: '/api/v1/get_mode',
    urlPost: '/api/v1/set_mode',
    urlModes: '/api/v1/modes',
  },
  schedules: {
    comercial: { ini1: '08:00', ini2: '14:00' },
    extendido: { ini1: '07:00', ini2: '22:00' },
    autoservicio: { ini1: '00:00', ini2: '23:59' },
    cerrado: { ini1: '22:00', ini2: '08:00' },
  },
  officeWithATM: false,
  emergency: {
    enabled: true,
    rule_key: 'pulsador_emergencia_verde_puerta_oficina',
    action: 'set_rule',
    output_code: '',
    output_on: true,
  },
  fireSignal: {
    enabled: true,
    rule_key: 'senal_de_incendio_activada',
    action: 'set_rule',
    output_code: '',
    output_on: true,
  },
  modes: {
    automatico: {
      rule_key: 'horario_automatico',
      action: 'set_rule',
      enabled: true,
      output_code: '',
      output_on: true,
    },
    esclusa: {
      rule_key: 'horario_esclusa',
      action: 'set_rule',
      enabled: true,
      output_code: '',
      output_on: true,
    },
    extendido: {
      rule_key: 'horario_extendido',
      action: 'set_rule',
      enabled: true,
      output_code: '',
      output_on: true,
    },
    autoservicio: {
      rule_key: 'horario_autoservicio',
      action: 'set_rule',
      enabled: true,
      output_code: '',
      output_on: true,
    },
    oficinaCerrada: {
      rule_key: 'horario_cerrado',
      action: 'set_rule',
      enabled: true,
      output_code: '',
      output_on: true,
    },
    cargaCajero: {
      rule_key: 'horario_carga_cajero',
      action: 'set_rule',
      enabled: true,
      output_code: '',
      output_on: true,
    },
    manual: {
      rule_key: 'horario_manual',
      action: 'set_rule',
      enabled: true,
      output_code: '',
      output_on: true,
    },
    incendio: {
      rule_key: 'senal_de_incendio_activada',
      action: 'set_rule',
      enabled: true,
      output_code: '',
      output_on: true,
    },
  },
  tabletCall: {
    enabled: true,
    timeoutSeconds: 30,
    modes: 'horario_manual,horario_carga_cajero',
    pulsadores: 'p1',
  },
  visualization: {
    autoStartCameras: true,
  },
  cargaCajero: {
    videoporteroDoorId: 'P2',
  },
};

export function cloneDefaultDoorAppConfig(): ConfigurationData {
  return JSON.parse(JSON.stringify(DEFAULT_DOOR_APP_CONFIGURATION));
}
